services:
    gateway:
        build:
            context: .
            dockerfile: services/gateway/Dockerfile
        environment:
            - GATEWAY_HOST=0.0.0.0
            - GATEWAY_PORT=3000
            - FIBONACCI_HOST=fibonacci
            - FIBONACCI_PORT=3001
        ports:
            - 3000:3000
    fibonacci:
        build:
            context: .
            dockerfile: services/fibonacci/Dockerfile
        environment:
            - FIBONACCI_HOST=0.0.0.0
            - FIBONACCI_PORT=3001
        ports:
            - 3001:3001
