packages:
    - services/*
    - packages/*
    - runners/*
    - toolings/*

catalog:
    typescript: ^5.8.2
    oxlint: ^1.1.0
    oxfmt: ^0.47.0

    # nest
    "@nestjs/common": ^11.0.0
    "@nestjs/core": ^11.0.0
    "@nestjs/microservices": ^11.0.0
    "@nestjs/platform-fastify": ^11.0.0
    "@nestjs/typeorm": ^11.0.0
    "@nestjs/cli": 11.0.21
    reflect-metadata: ^0.2.2
    rxjs: ^7.8.1

    # auth / persistence
    bcryptjs: ^2.4.3
    pg: ^8.13.0
    typeorm: ^0.3.20
    zod: ^3.23.8

    # testing
    vitest: ^2.1.0
