export const REALTIME_EVENT_TYPES = [
    'realtime.connected',
    'realtime.ping',
    'room.ready',
    'topic.revealed',
    'sides.assigned',
    'prep.started',
    'debate.started',
    'message.created',
    'vote.created',
    'vote.updated',
    'result.published',
    'leaderboard.updated',
] as const;

export type RealtimeEventType = (typeof REALTIME_EVENT_TYPES)[number];

export interface RealtimeEventBase<
    TType extends RealtimeEventType = RealtimeEventType,
    TPayload extends object = object,
> {
    type: TType;
    roomId?: string;
    userId?: string;
    payload: TPayload;
    /**
     * RFC 3339 / ISO 8601 timestamp generated by the producer.
     */
    occurredAt: string;
}

export interface RealtimeConnectedPayload {
    stream: 'room' | 'debate' | 'user' | 'leaderboard';
    streamId: string;
}

export type RealtimePingPayload = Record<string, never>;

export interface RoomReadyPayload {
    roomId: string;
    debateId?: string;
    participantCount?: number;
}

export interface TopicRevealedPayload {
    topicId?: string;
    title?: string;
    text?: string;
}

export interface SideAssignment {
    userId: string;
    side: string;
}

export interface SidesAssignedPayload {
    assignments: SideAssignment[];
}

export interface PrepStartedPayload {
    startedAt: string;
    endsAt?: string;
    durationSeconds?: number;
}

export interface DebateStartedPayload {
    debateId?: string;
    startedAt: string;
    endsAt?: string;
    durationSeconds?: number;
}

export interface MessageCreatedPayload {
    messageId: string;
    authorUserId: string;
    body?: string;
    createdAt: string;
}

export interface VotePayload {
    voteId: string;
    debateId: string;
    userId: string;
    side: string;
    createdAt?: string;
    updatedAt?: string;
}

export interface ResultScore {
    side: string;
    score: number;
}

export interface ResultPublishedPayload {
    resultId?: string;
    debateId?: string;
    winningSide?: string;
    scores?: ResultScore[];
}

export interface LeaderboardEntry {
    userId: string;
    rank: number;
    score: number;
}

export interface LeaderboardUpdatedPayload {
    scope?: 'global' | 'room' | 'debate';
    entries: LeaderboardEntry[];
}

export type RealtimeEvent =
    | RealtimeEventBase<'realtime.connected', RealtimeConnectedPayload>
    | RealtimeEventBase<'realtime.ping', RealtimePingPayload>
    | RealtimeEventBase<'room.ready', RoomReadyPayload>
    | RealtimeEventBase<'topic.revealed', TopicRevealedPayload>
    | RealtimeEventBase<'sides.assigned', SidesAssignedPayload>
    | RealtimeEventBase<'prep.started', PrepStartedPayload>
    | RealtimeEventBase<'debate.started', DebateStartedPayload>
    | RealtimeEventBase<'message.created', MessageCreatedPayload>
    | RealtimeEventBase<'vote.created', VotePayload>
    | RealtimeEventBase<'vote.updated', VotePayload>
    | RealtimeEventBase<'result.published', ResultPublishedPayload>
    | RealtimeEventBase<'leaderboard.updated', LeaderboardUpdatedPayload>;
